# Generated by Django 3.0.5 on 2020-04-10 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_holder', models.CharField(max_length=200, null=True)),
                ('holder_org_name', models.CharField(max_length=200, null=True)),
                ('org_fax', models.FloatField(max_length=10, null=True)),
                ('org_CIN_number', models.CharField(max_length=200, null=True)),
            ],
        ),
    ]
